apiVersion: v2
appVersion: 2.0.2
description: A platform for developing guided interviews and expert systems
name: docassemble
version: 2.0.2
dependencies:
  - name: minio
    version: 14.7.3
    repository: https://charts.bitnami.com/bitnami
    condition: inClusterMinio
  - name: ingress-nginx
    version: 4.11.2
    repository: https://kubernetes.github.io/ingress-nginx
    condition: inClusterNGINX
  - name: rabbitmq
    version: 14.6.9
    repository: https://charts.bitnami.com/bitnami
    condition: inClusterRabbitMQ
  - name: redis
    version: 20.0.3
    repository: https://charts.bitnami.com/bitnami
    condition: inClusterRedis
  - name: postgresql
    version: 15.5.26
    repository: https://charts.bitnami.com/bitnami
    condition: inClusterPostgres
